### ISSUE TITLE
"Invalid Installer" On NOENT (For Files That Do Exist)

### ISSUE THREAD

**Issue by effs** [Nexus-Mods/vortex-api#29]
https://github.com/Nexus-Mods/Vortex/blob/f30cf8461a9aef6cb0f1cd515daa51200444e377/src/extensions/mod_management/InstallManager.ts#L2575

This condition is puzzling. What is the reason that we'd end up with 'missing files' when there is a 1:1 match between the set of files given to InstallFunc and the instructions produced?

(The error messaging isn't great either, it's not a mod problem, it's an extension problem.)

**Comment by TanninOne** [comment]
I don't know what you're talking about, you provide no context.
"copies" is a list of copy instructions provided by an installer, like a fomod or a game-specific installer provided with the game extension.
ENOENT is the operating system telling us that the file doesn't exist.

This indicates that either the installer is incorrect or that the user (or their system for whatever reason) deleted files while the installation was happening.
The one thing that can not happen is that "ENOENT" is reported when the file in question exists, permission problems for example would trigger a different error code.
