### ISSUE TITLE
Typo: `nexusOpenModMage` should be `nexusOpenModPage`

### ISSUE THREAD

**Issue by toebeann** [Nexus-Mods/vortex-api#37]
From https://github.com/Nexus-Mods/vortex-api/blob/master/lib/extensions/nexus_integration/types/INexusAPIExtension.d.ts#L22
```ts
    nexusOpenModMage?: (gameId: string, modId: string, source: string) => void;
```

Should this not be `nexusOpenModPage`? With a 'P' for 'Page'? 😅

I've tested this with a Vortex extension and the incorrect spelling definitely works so clearly this typo is in the underlying source JavaScript and not just in the typings, however I don't have access to the JavaScript source to raise the issue there.

**Comment by toebeann** [comment]
Just found another typo on [line 14](https://github.com/Nexus-Mods/vortex-api/blob/master/lib/extensions/nexus_integration/types/INexusAPIExtension.d.ts#L14):
```ts
    nexusGetLatestMods?: (gaemId: string) => PromiseLike<any>;
```
`gaemId` should be `gameId`

**Comment by TanninOne** [comment]
good catch!
Just fixed it
These typing are generated from the main application btw (Nexus-Mods/Vortex), that's where the actual code lives.
